### ISSUE TITLE
Prompt Tuning returns low-quality results

### ISSUE THREAD

**Issue by weidotwisc** [foundation-model-stack/fms-hf-tuning#103]
## Describe the bug

Prompt Tuning model generates low-quality output

## Platform

Please provide details about the environment you are using, including the following:

- Interpreter version: python 3.11.0
- Library version: transformers 4.37.2 peft 0.8.2

## Sample Code
My launching script is
```bash
export MODEL_PATH=/dccstor/ai4code-ansible/shared/ckpt/granite-20b-code-all-yaml-2k/
export DATA_PATH=/dccstor/weiz/peft/train.json
export OUTPUT_PATH=pt_ckpts
export CUDA_VISIBLE_DEVICES=0
export PYTHONPATH=.
python tuning/sft_trainer.py  \
--model_name_or_path $MODEL_PATH  \
--training_data_path $DATA_PATH  \
--output_dir $OUTPUT_PATH  \
--peft_method "pt" \
--tokenizer_name_or_path $MODEL_PATH  \
--num_train_epochs 5  \
--per_device_train_batch_size 2  \
--per_device_eval_batch_size 1  \
--gradient_accumulation_steps 1  \
--evaluation_strategy "no"  \
--save_strategy "epoch"  \
--learning_rate 3e-2  \
--weight_decay 0.  \
--warmup_ratio 0.0  \
--lr_scheduler_type "linear"  \
--logging_steps 1  \
--include_tokens_per_second  \
--packing False  \
--response_template "\n### Response:"  \
--dataset_text_field "output" \
--use_flash_attn True  \
--torch_dtype "bfloat16" \
       --num_virtual_tokens 100 \
       --max_seq_length 512 \
--prompt_tuning_init RANDOM
```
To repeat, one needs to define MODEL_PATH to the yaml-2k path (which is shared via COS bucket) and DATA_PATH to the training data

## Expected behavior
Using the first *training* data item as the input to the model should show something close to the ground truth, i.e.,  
```
community.docker.docker_login:                                                                                                                         
    registry: "{{ hostvars[groups['docker_registry'][0]].ansible_host }}:{{ registry_port }}"                                                            
    username: "{{ registry_username }}"                                                                                                                  
    password: "{{ registry_password }}"     
``` 

## Observed behavior
When running through inference, I got
```
.,.,.,.,.,.,.,.,.,.,........,.,.,.,.,...,.,.....,..,...,......,:.: -.:.:.:.:.:.:.............,........,..........,.:..........,.........,::::::::::::::::
::::::......:..............,.............,..............,.,..:.......:.........2.2......................      
```

## Additional context

- The SFT training loss has looked absolutely normal though. 

- I was able to adapt the HF PT tutorial at https://huggingface.co/docs/peft/main/en/task_guides/clm-prompt-tuning to run our task to get reasonable results.

**Comment by weidotwisc** [comment]
[train.json](https://github.com/foundation-model-stack/fms-hf-tuning/files/14795890/train.json)
The attached is the training data.

**Comment by weidotwisc** [comment]
Hi, I think I found the problem:

I used the flash attention, so in the inference code, we would need the extra flag 
```_attn_implementation="flash_attention_2"``` when loading model.

Thanks!

**Comment by weidotwisc** [comment]
I feel it probably worths noting this down in the inference document  so that the consumer of this model needs to be aware of this particular flash attention flag as it requires changes to downstream inference pipeline code.

**Comment by fabianlim** [comment]
@weidotwisc on second thoughts im a little puzzled. FA2 is a drop-in replacement for the attention layer, which only speeds up the compute, but should not affect the result. As such, regardless if you had trained in FA2, during inference it should not matter if you had set FA2 or not.

**Comment by weidotwisc** [comment]
For what I have observed, if we use SFT trainer code and specify 
```--use_flash_attn False```, then the inference model loading code should be:
```model = AutoModelForCausalLM.from_pretrained(config.base_model_name_or_path, torch_dtype=torch.bfloat16)```

If we use SFT trainer code and specify ```--use_flash_attn True```, then the inference model loading code should be:
```model = AutoModelForCausalLM.from_pretrained(config.base_model_name_or_path, torch_dtype=torch.bfloat16, _attn_implementation="flash_attention_2")```

**Comment by Ssukriti** [comment]
@weidotwisc could you also share you test set and evaluation script if you have it?

**Comment by olson-ibm** [comment]
Trying to reproduce this issue using the platform testing environment `DevStage`.

This process is being documented [here](https://github.ibm.com/ai-foundation/watson-fm-stack-tracker/issues/733).

@weidotwisc I don't have access to the data set you used to train, `export DATA_PATH=/dccstor/weiz/peft/train.json`. How can I get it? Your directory on CCC is not accessible with my CCC credentials. Can you copy temporarily copy it to one of the public `/dccstor/ai4code-ansible` directories? I'll delete it as soon as I get it.

**Comment by weidotwisc** [comment]
Thanks @olson-ibm !
@Ssukriti  -- The evaluation pipeline is a little tough to set up -- it requires some artifacts credentials to install some specific ansible related libraries and then some set up for post processing before calling into a pytest-based environment. 
However, to repeat this flash attention related issue, you can pick a sample from the input dataset and let pt-tuned model to generate output, the results will be looking gibberish like 
```.,.,.,.,.,.,.,.,.,.,........,.,.,.,.,...,.,.....,..,...,......,:.: -.:.:.:.:.:.:.............,........,..........,.:..........,.........,::::::::::::::::
::::::......:..............,.............,..............,.,..:.......:.........2.2......................     
```
instead of any reasonable yaml-like output such as 
```
community.docker.docker_login:                                                                                                                         
    registry: "{{ hostvars[groups['docker_registry'][0]].ansible_host }}:{{ registry_port }}"                                                            
    username: "{{ registry_username }}"                                                                                                                  
    password: "{{ registry_password }}"     
```
