### ISSUE TITLE
feat: standardize the format for metrics, operations, controls in the yamls used by `TrainerControllerCallback`

### ISSUE THREAD

**Issue by HarikrishnanBalagopal** [foundation-model-stack/fms-hf-tuning#129]
## Is your feature request related to a problem? Please describe.

Current format
```yaml
controller-metrics:
    loss:
        Loss:
  - name: sparsity
    class: Sparsity
    args:
       key3: val3
       key4: val4
```

## Describe the solution you'd like

New format

```yaml
controller-metrics:
  - name: loss-one
    class: Loss
    arguments:
       key-num-1: val1
       key-num-2: val2
  - name: sparsity-one
    class: Sparsity
    arguments:
       key-num-3: val3
       key-num-4: val4
operations:
  - name: op1
    class: MyOperation1
controllers:
  - name: loss-controller
    triggers:
      - on_log
    rule: loss-one < 1.0
    operations:
      - hfcontrols.should_training_stop
```
