### ISSUE TITLE
feat: Expose the trainer state as a trainer controller metric

### ISSUE THREAD

**Issue by seshapad** [foundation-model-stack/fms-hf-tuning#134]
## Is your feature request related to a problem? Please describe.

This feature is an add-on to the trainer controller framework. We add a new metric to this framework to expose the trainer state of the trainer loop.

## Describe the solution you'd like

This metric now enables rules like the below example, wherein we could check the epochs elapsed in order to stop training on a loss threshold.
```
controller-metrics:
  - name: state
    class: StateOfTrainer
  - name: loss
    class: Loss
controllers:
  - name: loss-controller
    triggers:
      - on_log
    rule: loss < 2.2 and state['epoch'] > 5
    operations:
      - hfcontrols.should_training_stop
```

## Describe alternatives you've considered

We checked if the trainer state is a call-by-reference object which could be obtained once and referred many-times, but this is not how the trainer loop exposes the trainer state. The only way we could find the trainer state to be exposed is in through the arguments of the events of trainer callback.

## Additional context

NA
